eth:
  outputs:
    ci:
      account: KSKTFGU-JW82895
      database: CI
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH')}}"
      role: ACCOUNTADMIN
      schema: CI_SCHEMA
      threads: 1
      type: snowflake
      user: daniel
      warehouse: compute_wh
  target: ci