eth:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: KSKTFGU-JW82895
      user: daniel
      role: ACCOUNTADMIN
      warehouse: compute_wh
      database: CI
      schema: ci_schema
      threads: 1
      private_key_path: /home/runner/.dbt/rsa_key.p8
