# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'eth'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'eth'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"



flags:
  fail_fast: true


seeds:
  +database: seeds
  +schema: static


models:
  eth:
    +materialized: table
    +tags: ['eth', 'crypto']
    marts:
      +tags:
        - powerbi
        - report
      +schema: marts


      stablecoin_activity_per_day:
        +post-hook:
          - GRANT USAGE ON DATABASE DBT TO ROLE TESTER;
          - GRANT USAGE ON SCHEMA DBT.DBT_DWEIGEL_MARTS TO ROLE TESTER;
          - GRANT USAGE ON DATABASE DBT TO ROLE BA;
          - GRANT USAGE ON SCHEMA DBT.DBT_DWEIGEL_MARTS TO ROLE BA;
          - "{{ create_latest_version_view() }}"
        +grants:
          select: []


vars:
  # token_name_var: 'tron'
  # token_address_var: '0x50327c6c5a14dcade707abad2e27eb517df87ab5'
  # token_decimals_var: '6'
  token_name_var: 'link'
  token_address_var: '0x514910771af9ca656af840dff83e8264ecf986ca'
  token_decimals_var: '18'


dispatch:
  - macro_namespace: dbt_utils
    search_order: ['eth', 'dbt_utils']