version: 2


models:
  - name: stg_transactions
    description: "Transactions in the Ethereum Blockchain"
    columns:
      - name: hash
        description: >
          This is a very long multiline description about the unique
          identifier of each transaction in the Ethereum blockchain
        data_tests:
          - unique
          - not_null

  - name: stablecoin_activity_per_day
    latest_version: 2
    config:
      contract:
        enforced: true
        alias_types: false
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: string
        description: ""

      - name: type
        data_type: varchar
        description: ""

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""
    
    versions:
    
      - v: 1
        deprecation_date: 2030-01-01
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [token_address, symbol]



# semantic_models:
#   - name: the_name_of_the_semantic_model ## Required
#     description: same as always ## Optional
#     model: ref('eth_activity_per_day') ## Required
#     defaults: ## Required
#       agg_time_dimension: dimension_name ## Required if the model contains measures
#     entities: ## Required
#       - see more information in entities
#     measures: ## Optional
#       - see more information in the measures section
#     dimensions: ## Required
#       - see more information in the dimensions section
#     primary_entity: >-
#       if the semantic model has no primary entity, then this property is required. #Optional if a primary entity exists, otherwise Required
