version: 2


models:

  - name: stg_token_transfers
    columns:
      - name: transaction_hash
        data_tests:
          - relationships:
              to: ref('stg_transactions')
              field: hash

  - name: stg_transactions_enriched
    columns:
      - name: value
        data_tests:
          - assert_value_amount_positive:
              field: block_number

  - name: stg_transactions
    description: "Transactions in the Ethereum Blockchain"
    columns:
      - name: hash
        description: >
          This is a very long multiline description about the unique
          identifier of each transaction in the Ethereum blockchain
        data_tests:
          - unique
          - not_null

  - name: stablecoin_activity_per_day
    latest_version: 2
    config:
      contract:
        enforced: true
        alias_types: false
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: string
        description: ""

      - name: type
        data_type: varchar
        description: ""
        data_tests:
          - accepted_values:
              values: ['Hybrid', 'Crypto-backed', 'Fiat-backed']

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""
    
    versions:
    
      - v: 1
        deprecation_date: 2030-01-01
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [token_address, symbol]
