version: 2

sources:
  - name: eth
    database: eth  
    schema: eth_schema

    tables:
      - name: contracts
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 40, period: day}
        loaded_at_field: to_timestamp(date) 
      - name: contracts_clone
      - name: token_transfers
      - name: transactions

