version: 2

sources:
  - name: eth
    database: eth  
    schema: eth_schema  
    tables:
      - name: contracts
      - name: contracts_clone
      - name: token_transfers
      - name: transactions

